import { UserProfile, FirmProfile, FirmMember, CaseFile, HearingItem, InvoiceItem } from '../types';

export interface DemoAccountDefinition {
  id: 'firm' | 'student';
  title: string;
  subtitle: string;
  tag: string;
  icon: string;
  user: {
    uid: string;
    email: string;
    displayName: string;
  };
  profile: UserProfile;
  firm?: FirmProfile;
  firmMembers?: FirmMember[];
  cases: CaseFile[];
  hearings: HearingItem[];
  invoices: InvoiceItem[];
}

export const DEMO_ACCOUNTS: Record<'firm' | 'student', DemoAccountDefinition> = {
  firm: {
    id: 'firm',
    title: 'Sharma & Associates (Chambers)',
    subtitle: 'Managing Partner · 16 Yrs Exp · Delhi High Court',
    tag: 'Law Firm Chambers',
    icon: 'Building2',
    user: {
      uid: 'demo-chambers-sharma',
      email: 'chambers.demo@nyaayneeti.in',
      displayName: 'Adv. Rajesh Sharma & Associates',
    },
    profile: {
      uid: 'demo-chambers-sharma',
      name: 'Adv. Rajesh Sharma & Associates',
      role: 'firm_admin',
      phone: '+91 98101 23456',
      email: 'chambers.demo@nyaayneeti.in',
      photoURL: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&q=80&w=250',
      state: 'Delhi',
      city: 'New Delhi',
      onboardingCompleted: true,
      verificationStatus: 'verified',
      barCouncilId: 'D/1482/2008',
      barAssociation: 'Delhi High Court Bar Association (DHCBA)',
      practiceType: 'firm',
      firmName: 'Sharma & Associates Legal Chambers',
      chambersAddress: 'Chambers 402, Lawyers Chambers Block III, Delhi High Court, New Delhi 110003',
      chamberGeo: {
        lat: 28.6139,
        lng: 77.241,
        formattedAddress: 'Chambers 402, Lawyers Chambers Block III, Delhi High Court',
        city: 'New Delhi',
        state: 'Delhi',
        geohash: 'ttngk',
        updatedAt: '2026-09-29T10:00:00.000Z',
      },
      practiceCourts: ['Supreme Court of India', 'Delhi High Court', 'Patiala House District Courts', 'NCLAT'],
      practiceAreas: ['Commercial Disputes', 'Corporate Arbitration', 'Civil Appeals', 'Writ Petitions'],
      experience: 16,
      education: ['LL.M. (Commercial Law) — National Law University Delhi', 'LL.B. — Faculty of Law, DU'],
      languages: ['English', 'Hindi'],
      feeRange: { min: 25000, max: 150000 },
      rating: 4.9,
      totalCases: 142,
      bio: 'Managing Partner at Sharma & Associates. Practicing before the Supreme Court of India and Delhi High Court with specialization in commercial arbitrations, infrastructure disputes, and company law.',
    },
    firm: {
      id: 'firm-sharma-chambers',
      firmName: 'Sharma & Associates Legal Chambers',
      institutionType: 'firm',
      firmRegistrationId: 'DHC/CH/2012/048',
      gstPan: '07AAAFS1234F1Z8',
      address: 'Chambers 402, Lawyers Chambers Block III, Delhi High Court, New Delhi 110003',
      adminEmail: 'chambers.demo@nyaayneeti.in',
      adminUid: 'demo-chambers-sharma',
      memberCount: 5,
      createdAt: '2024-01-15T00:00:00.000Z',
    },
    firmMembers: [
      {
        id: 'mem-1',
        firmId: 'firm-sharma-chambers',
        name: 'Adv. Rajesh Sharma',
        email: 'chambers.demo@nyaayneeti.in',
        role: 'associate',
        mustChangePassword: false,
        joinedAt: '2024-01-15',
      },
      {
        id: 'mem-2',
        firmId: 'firm-sharma-chambers',
        name: 'Adv. Priya Deshmukh',
        email: 'priya.deshmukh@sharmalegal.in',
        role: 'associate',
        mustChangePassword: false,
        joinedAt: '2024-06-01',
      },
      {
        id: 'mem-3',
        firmId: 'firm-sharma-chambers',
        name: 'Adv. Vikramaditya Sen',
        email: 'vikram.sen@sharmalegal.in',
        role: 'junior',
        mustChangePassword: false,
        joinedAt: '2025-02-15',
      },
      {
        id: 'mem-4',
        firmId: 'firm-sharma-chambers',
        name: 'Kavita Iyer',
        email: 'kavita.i@sharmalegal.in',
        role: 'paralegal',
        mustChangePassword: false,
        joinedAt: '2025-04-10',
      },
      {
        id: 'mem-5',
        firmId: 'firm-sharma-chambers',
        name: 'Rohan Mehra',
        email: 'rohan.intern@sharmalegal.in',
        role: 'student',
        mustChangePassword: false,
        joinedAt: '2026-01-08',
      },
    ],
    cases: [
      {
        id: 'case-sharma-1',
        caseNumber: 'ARB/402/2026',
        clientName: 'Apex Infrastructure Ltd',
        clientPhone: '+91 98112 00451',
        opponentName: 'National Highways & Metro Rail Authority',
        court: 'High Court',
        courtLocation: 'Delhi High Court',
        caseType: 'Arbitration Petition',
        actSections: ['Section 34 Arbitration & Conciliation Act 1996'],
        status: 'Active',
        stage: 'Final Arguments',
        filingDate: '2025-08-14',
        nextHearingDate: 'Today, 10:30 AM',
        totalBilled: 150000,
        totalCollected: 100000,
        unreadDocuments: 2,
        pendingChecklistItems: 1,
      },
      {
        id: 'case-sharma-2',
        caseNumber: 'WP(C)/8120/2025',
        clientName: 'Singhal Metal & Alloys',
        clientPhone: '+91 98230 45678',
        opponentName: 'Commissioner of Customs & Central GST',
        court: 'High Court',
        courtLocation: 'Delhi High Court',
        caseType: 'Civil Writ Petition',
        actSections: ['Article 226 Constitution of India', 'Section 130 CGST Act'],
        status: 'Active',
        stage: 'Evidence',
        filingDate: '2025-11-03',
        nextHearingDate: 'Tomorrow, 02:00 PM',
        totalBilled: 95000,
        totalCollected: 95000,
        unreadDocuments: 0,
        pendingChecklistItems: 0,
      },
      {
        id: 'case-sharma-3',
        caseNumber: 'CS(COMM)/129/2026',
        clientName: 'Delta BioSciences Pvt Ltd',
        clientPhone: '+91 98450 11223',
        opponentName: 'Matrix Therapeutics',
        court: 'District Court',
        courtLocation: 'Patiala House Commercial Court',
        caseType: 'Commercial Suit',
        actSections: ['Commercial Courts Act 2015', 'Section 27 Trade Marks Act'],
        status: 'Active',
        stage: 'Admission',
        filingDate: '2026-02-18',
        nextHearingDate: '15 Oct 2026',
        totalBilled: 60000,
        totalCollected: 30000,
        unreadDocuments: 1,
        pendingChecklistItems: 2,
      },
    ],
    hearings: [
      {
        id: 'hr-sharma-1',
        caseNumber: 'ARB/402/2026',
        clientName: 'Apex Infrastructure Ltd',
        courtName: 'Delhi High Court',
        courtRoom: 'Court No. 14 (Justice K.R. Rao)',
        hearingDate: 'Today, 10:30 AM',
        itemNumber: 8,
        judgeName: 'Hon\'ble Justice K.R. Rao',
        stage: 'Final Arguments',
        purposeEn: 'Final arguments on Section 34 objection petition against arbitral award',
        purposeHi: 'पंचाट के विरुद्ध धारा 34 आपत्ति याचिका पर अंतिम बहस',
      },
      {
        id: 'hr-sharma-2',
        caseNumber: 'WP(C)/8120/2025',
        clientName: 'Singhal Metal & Alloys',
        courtName: 'Delhi High Court',
        courtRoom: 'Court No. 3 (Division Bench)',
        hearingDate: 'Tomorrow, 02:00 PM',
        itemNumber: 22,
        judgeName: 'Hon\'ble Justice S. Muralidhar & Justice P.K. Jain',
        stage: 'Evidence',
        purposeEn: 'Cross-examination and submission of export consignment reconciliation',
        purposeHi: 'निर्यात खेप समाधान प्रस्तुत करना व जिरह',
      },
    ],
    invoices: [
      {
        id: 'inv-sharma-1',
        invoiceNumber: 'INV-2026-081',
        caseNumber: 'ARB/402/2026',
        clientName: 'Apex Infrastructure Ltd',
        totalAmount: 150000,
        appearanceFee: 100000,
        draftingFee: 35000,
        clerkageAndMisc: 15000,
        status: 'Pending',
        date: '2026-09-20',
      },
      {
        id: 'inv-sharma-2',
        invoiceNumber: 'INV-2026-074',
        caseNumber: 'WP(C)/8120/2025',
        clientName: 'Singhal Metal & Alloys',
        totalAmount: 95000,
        appearanceFee: 70000,
        draftingFee: 20000,
        clerkageAndMisc: 5000,
        status: 'Paid',
        date: '2026-09-05',
      },
    ],
  },

  student: {
    id: 'student',
    title: 'Aarav Patel (Law Student Intern)',
    subtitle: 'Campus Law Centre (DU) · LL.B. 3rd Year · Research Intern',
    tag: 'Law Student & Intern',
    icon: 'GraduationCap',
    user: {
      uid: 'demo-student-aarav',
      email: 'student.demo@nyaayneeti.in',
      displayName: 'Aarav Patel (Student Intern)',
    },
    profile: {
      uid: 'demo-student-aarav',
      name: 'Aarav Patel',
      role: 'student',
      phone: '+91 97110 98765',
      email: 'student.demo@nyaayneeti.in',
      photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
      state: 'Delhi',
      city: 'Delhi',
      onboardingCompleted: true,
      verificationStatus: 'verified',
      barCouncilId: 'CLC/DU/2023/8491 (Student Enrollment)',
      barAssociation: 'Delhi University Legal Services Clinic (DULSC)',
      practiceType: 'independent',
      firmName: 'Campus Law Centre (DU) Legal Clinic',
      chambersAddress: 'Campus Law Centre, Faculty of Law, Chhatra Marg, North Campus, Delhi 110007',
      chamberGeo: {
        lat: 28.6946,
        lng: 77.2155,
        formattedAddress: 'Campus Law Centre, Chhatra Marg, North Campus, Delhi 110007',
        city: 'Delhi',
        state: 'Delhi',
        geohash: 'ttnhe',
        updatedAt: '2026-09-29T10:00:00.000Z',
      },
      practiceCourts: ['Tis Hazari District Courts', 'Delhi High Court', 'Campus Moot Court Hall'],
      practiceAreas: ['Criminal Procedure (BNSS/BNS)', 'Constitutional Law', 'Legal Aid & Human Rights'],
      experience: 1,
      education: ['LL.B. (Candidate, 3rd Year) — Campus Law Centre, Faculty of Law, University of Delhi', 'B.A. (Hons) Political Science — Ramjas College, DU'],
      languages: ['English', 'Hindi', 'Gujarati'],
      rating: 4.8,
      totalCases: 12,
      bio: 'Final year LL.B. student at Campus Law Centre, DU. Legal research intern focusing on statutory transitions under Bharatiya Nyaya Sanhita (BNS) and Bharatiya Nagarik Suraksha Sanhita (BNSS). Student volunteer at DULSC legal aid clinic.',
    },
    cases: [
      {
        id: 'case-student-1',
        caseNumber: 'BAIL/108/2026',
        clientName: 'State vs Ramesh Kumar',
        clientPhone: '+91 98110 00000',
        opponentName: 'State (NCT of Delhi)',
        court: 'Sessions Court',
        courtLocation: 'Tis Hazari District Courts',
        caseType: 'Regular Bail Application',
        actSections: ['Section 480 BNSS 2023 (Old 439 CrPC)', 'Section 303(2) BNS 2023 (Theft)'],
        status: 'Active',
        stage: 'Admission',
        filingDate: '2026-09-18',
        nextHearingDate: 'Today, 02:30 PM',
        totalBilled: 0,
        totalCollected: 0,
        unreadDocuments: 1,
        pendingChecklistItems: 1,
      },
      {
        id: 'case-student-2',
        caseNumber: 'MOOT/DLC/2026',
        clientName: 'DU National Moot Court Exercise',
        clientPhone: '+91 98110 00001',
        opponentName: 'Union of India (Inter-College)',
        court: 'High Court',
        courtLocation: 'Faculty Moot Court Hall',
        caseType: 'Constitutional Appellate Review',
        actSections: ['Article 19(1)(a)', 'Article 21 Constitution of India', 'Digital Personal Data Protection Act 2023'],
        status: 'Active',
        stage: 'Final Arguments',
        filingDate: '2026-09-01',
        nextHearingDate: 'Tomorrow, 11:00 AM',
        totalBilled: 0,
        totalCollected: 0,
        unreadDocuments: 3,
        pendingChecklistItems: 0,
      },
    ],
    hearings: [
      {
        id: 'hr-student-1',
        caseNumber: 'BAIL/108/2026',
        clientName: 'State vs Ramesh Kumar',
        courtName: 'Tis Hazari Sessions Court',
        courtRoom: 'Court No. 28 (ASJ Central)',
        hearingDate: 'Today, 02:30 PM',
        itemNumber: 4,
        judgeName: 'Hon\'ble ASJ Verma',
        stage: 'Admission',
        purposeEn: 'Bail hearing observation & assisting senior counsel with case law compilation',
        purposeHi: 'जमानत सुनवाई अवलोकन व नज़ीरों का संकलन',
      },
      {
        id: 'hr-student-2',
        caseNumber: 'MOOT/DLC/2026',
        clientName: 'DU National Moot Court Exercise',
        courtName: 'Campus Law Centre',
        courtRoom: 'Moot Bench Room 1',
        hearingDate: 'Tomorrow, 11:00 AM',
        itemNumber: 3,
        judgeName: 'Presiding Senior Advocate Bench',
        stage: 'Final Arguments',
        purposeEn: 'Appellate oral submissions on privacy and constitutional limitations',
        purposeHi: 'निजता एवं संवैधानिक सीमाओं पर मौखिक बहस',
      },
    ],
    invoices: [],
  },
};
